services:
  db:
    image: vothanhluan/ielts-aptis-db:latest
    container_name: ielts_aptis_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: ielts_platform
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

  backend:
    image: vothanhluan/ielts-aptis-backend:latest
    container_name: ielts_aptis_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:123456@db:5432/ielts_platform
      - SECRET_KEY=9b7c2a1d4f8e6c5a3b2d1f0e9c8b7a6d5f4e3c2b1a0d9e8f7c6b5a4d3c2b1a0f
      - ACCESS_TOKEN_EXPIRE_MINUTES=1200
      - GEMINI_API_KEY=AIzaSyD_4xJgfBY56qdbEiO-hGgTnmtWCXEU4S0
      - GOOGLE_CLIENT_ID=251893554534-skskt9risg1c3jofn8k3489ce4dhdrve.apps.googleusercontent.com
      - CLOUDINARY_CLOUD_NAME=kexinnvd
      - CLOUDINARY_API_KEY=934551637461136
      - CLOUDINARY_API_SECRET=lKs242fxHqqSL1AgM0VTWga1qW8
      - USE_CLOUDINARY=True
      - BASE_URL=https://english.greenwich-it.com
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    image: vothanhluan/ielts-aptis-frontend:latest
    container_name: ielts_aptis_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
